version: '3'

services:
  php:
    container_name: php2
    build: ./docker/php
    volumes:
    - ./webapp:/var/www

  nginx:
    image: nginx
    container_name: nginx2
    ports:
    - 8081:80
    volumes:
    - ./webapp:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    container_name: db-host2
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306